/**
 * CSRF double-submit token middleware for PT Buana Megah Job Portal.
 *
 * Strategy (Design §8.6 / Req 15.2):
 *   - The token itself is generated by `session-store.create()` at
 *     session-creation time and persisted in `sessions.csrf_token`. This
 *     module never mints a token; it only mirrors / verifies the value
 *     already bound to the session.
 *   - After login (and on any rotation) the auth flow calls `setCsrfCookie`
 *     to copy that token into a non-HttpOnly cookie named `csrf_token` so
 *     client-side JavaScript (htmx) can read it. The same value is rendered
 *     into `<meta name="csrf-token">` for non-htmx forms via `csrfMetaTag`.
 *   - For every state-changing request (POST/PUT/PATCH/DELETE) the
 *     `preHandler` hook installed by `registerCsrf` verifies that:
 *       1. A token is present on the request — either as the
 *          `X-CSRF-Token` header (htmx default) or as the `_csrf` form
 *          field (plain HTML forms).
 *       2. The cookie token, the request token, and the
 *          `sessions.csrf_token` row all agree (constant-time comparison
 *          via `crypto.timingSafeEqual`).
 *     Any failure short-circuits with HTTP 403.
 *   - Read methods (GET/HEAD/OPTIONS) are unaffected. Endpoints listed in
 *     the bypass set (default `['/healthz']`) skip the check entirely.
 *   - Unauthenticated requests (no `__Host-sid` cookie) also skip the
 *     check: there is no session token to bind against, and the spec
 *     scopes CSRF to "state-changing forms rendered to authenticated
 *     users" (Req 15.2). Routes such as login / registration rely on
 *     credential checks rather than CSRF.
 *
 * Public surface:
 *   - `registerCsrf(app, options?)`        — install the preHandler hook.
 *   - `setCsrfCookie(reply, token)`        — issue the csrf cookie.
 *   - `csrfMetaTag(token)`                 — render the meta tag markup.
 *   - `extractRequestToken(request)`       — read the request-side token.
 *   - `safeEqualToken(a, b)`               — timing-safe string equality.
 *   - Constants: `CSRF_HEADER_NAME`, `CSRF_FIELD_NAME`,
 *     `STATE_CHANGING_METHODS`, `DEFAULT_BYPASS_PATHS`,
 *     `CSRF_COOKIE_OPTIONS`.
 *
 * Validates: Requirements 15.2 (Design §8.6)
 */

import { timingSafeEqual } from 'node:crypto';

import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';

import {
  CSRF_COOKIE_NAME,
  SESSION_COOKIE_NAME,
  TOKEN_LENGTH,
  read as readSession,
} from './session-store.js';

// ---------------------------------------------------------------------------
// Public constants
// ---------------------------------------------------------------------------

/**
 * Re-export of the cookie name that carries the CSRF token. The constant
 * lives in `session-store.ts` (alongside the session cookie name) but is
 * conceptually part of the CSRF surface, so we expose it from this module
 * as well. Callers that need to clear or read the cookie (e.g. the
 * auth-guard logout redirect) import it from here together with
 * `CSRF_COOKIE_OPTIONS`, keeping the CSRF cookie's name and attributes
 * in a single module.
 */
export { CSRF_COOKIE_NAME };

/**
 * HTTP request header that carries the CSRF token. Matches the htmx
 * default (`htmx.config.csrfHeaderName === 'X-CSRF-Token'`); Node lowercases
 * incoming header names so the constant is stored in lower case.
 */
export const CSRF_HEADER_NAME = 'x-csrf-token';

/** Form field name used by plain HTML `<form>` submissions. */
export const CSRF_FIELD_NAME = '_csrf';

/**
 * Methods that mutate server state and therefore require a CSRF token.
 * GET/HEAD/OPTIONS are RFC-7231 "safe" methods and are excluded.
 */
export const STATE_CHANGING_METHODS: ReadonlySet<string> = new Set([
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
]);

/**
 * Default paths that bypass CSRF verification entirely. `/healthz` is the
 * only canonical bypass — it accepts no body and runs `SELECT 1`.
 * Additional bypasses can be supplied per-app via `registerCsrf` options.
 */
export const DEFAULT_BYPASS_PATHS: readonly string[] = ['/healthz'];

/**
 * Cookie attributes for the non-HttpOnly `csrf_token` cookie. Mirrors the
 * session cookie in every dimension except `httpOnly`, which must be off
 * so client-side JavaScript (htmx) can read the value. `Secure` and
 * `SameSite=Lax` keep the cookie from leaking across origins.
 *
 * Frozen so callers can spread it into `reply.setCookie(...)` without
 * accidentally mutating the shared object.
 */
export const CSRF_COOKIE_OPTIONS = Object.freeze({
  httpOnly: false,
  secure: true,
  sameSite: 'lax' as const,
  path: '/',
});

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

/** Options accepted by `registerCsrf`. */
export interface CsrfOptions {
  /**
   * Paths that bypass the CSRF check. Match is performed against the
   * pathname portion of `request.url` only (query string is stripped).
   * Defaults to `DEFAULT_BYPASS_PATHS` (i.e. `['/healthz']`).
   */
  readonly bypassPaths?: readonly string[];
}

// ---------------------------------------------------------------------------
// Token issuance helpers
// ---------------------------------------------------------------------------

/**
 * Set the non-HttpOnly `csrf_token` cookie on a reply. Call this once
 * after creating or rotating a session so the browser begins presenting
 * the cookie. The cookie value MUST equal `sessions.csrf_token` for the
 * active session; rotating the token requires a fresh session row.
 */
export function setCsrfCookie(reply: FastifyReply, token: string): FastifyReply {
  return reply.setCookie(CSRF_COOKIE_NAME, token, CSRF_COOKIE_OPTIONS);
}

/**
 * Render the `<meta name="csrf-token" content="…">` markup snippet.
 *
 * The CSRF token format (43-char base64url) contains no HTML-significant
 * characters today, but we still escape `"` defensively in case the
 * encoding ever changes. Templates that already control attribute
 * encoding should pass the raw token to the layout context instead of
 * using this helper.
 */
export function csrfMetaTag(token: string): string {
  const safe = token.replace(/"/g, '&quot;');
  return `<meta name="csrf-token" content="${safe}">`;
}

// ---------------------------------------------------------------------------
// Verification helpers
// ---------------------------------------------------------------------------

/**
 * Constant-time equality for two CSRF token strings. Returns `false` when
 * either input is missing, non-string, or of a different byte length.
 *
 * Length is intentionally checked before `timingSafeEqual` because the
 * function throws on length mismatch; the early return collapses that
 * branch to a constant-cost comparison without leaking length differences
 * via exception side-channels (both branches return `false` synchronously).
 */
export function safeEqualToken(
  a: string | undefined | null,
  b: string | undefined | null,
): boolean {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  if (a.length !== b.length) return false;
  const bufA = Buffer.from(a, 'utf8');
  const bufB = Buffer.from(b, 'utf8');
  if (bufA.length !== bufB.length) return false;
  return timingSafeEqual(bufA, bufB);
}

/**
 * Extract the request-supplied CSRF token. Header `X-CSRF-Token` is checked
 * first (htmx); the `_csrf` form field is the fallback for non-JS clients.
 * Returns `null` when neither carries a usable string value.
 */
export function extractRequestToken(request: FastifyRequest): string | null {
  const headerVal = request.headers[CSRF_HEADER_NAME];
  if (typeof headerVal === 'string' && headerVal.length > 0) {
    return headerVal;
  }
  if (Array.isArray(headerVal)) {
    // Multiple `X-CSRF-Token` values are ambiguous; refuse rather than
    // pick one. Browsers never send duplicates for this header.
    return null;
  }

  const body = request.body;
  if (body !== null && typeof body === 'object') {
    const fromBody = (body as Record<string, unknown>)[CSRF_FIELD_NAME];
    if (typeof fromBody === 'string' && fromBody.length > 0) {
      return fromBody;
    }
  }

  return null;
}

// ---------------------------------------------------------------------------
// Plugin registration
// ---------------------------------------------------------------------------

/**
 * Pathname extracted from `request.url` (which always includes the query
 * string in Fastify). Splitting on `?` is safe because Node's HTTP parser
 * never produces a path containing a literal `?` ahead of the query.
 */
function pathnameOf(url: string): string {
  const queryStart = url.indexOf('?');
  return queryStart === -1 ? url : url.slice(0, queryStart);
}

/**
 * Send the canonical 403 response and short-circuit the route handler.
 * The reason code is intentionally generic (`csrf_invalid`) so the body
 * does not leak which of the three checks failed (cookie missing, request
 * token missing, mismatch with sessions row).
 */
function denyCsrf(
  app: FastifyInstance,
  request: FastifyRequest,
  reply: FastifyReply,
  reason: string,
): FastifyReply {
  app.log.warn(
    { reqId: request.id, method: request.method, url: request.url, reason },
    'csrf: rejected request',
  );
  reply.code(403).send({ error: 'csrf_invalid' });
  return reply;
}

/**
 * Register the CSRF preHandler hook on a Fastify instance.
 *
 * Ordering: this MUST run after `@fastify/cookie` (so `request.cookies` is
 * populated) and after `@fastify/formbody` / `@fastify/multipart` (so
 * `request.body` is parsed for the `_csrf` field). `registerSecurityHeaders`
 * has no ordering relationship with this hook.
 *
 * The hook is a no-op when:
 *   - `request.method` is not in `STATE_CHANGING_METHODS`;
 *   - the request pathname is in the bypass set (default `/healthz`); or
 *   - no `__Host-sid` cookie is present (request is unauthenticated and
 *     therefore out of scope per Req 15.2 — auth middleware will reject
 *     it later if the route requires a session).
 *
 * Otherwise the hook enforces the three-way match described at the top of
 * this file and short-circuits with 403 on any failure.
 */
export async function registerCsrf(
  app: FastifyInstance,
  options: CsrfOptions = {},
): Promise<void> {
  const bypass = new Set<string>(options.bypassPaths ?? DEFAULT_BYPASS_PATHS);

  app.addHook('preHandler', async (request, reply) => {
    if (!STATE_CHANGING_METHODS.has(request.method)) {
      return;
    }

    if (bypass.has(pathnameOf(request.url))) {
      return;
    }

    const sid = request.cookies[SESSION_COOKIE_NAME];
    if (typeof sid !== 'string' || sid.length !== TOKEN_LENGTH) {
      // Unauthenticated state-changing request (e.g. login form). CSRF
      // does not apply here per Req 15.2; auth/RBAC middleware enforces
      // any access control.
      return;
    }

    const cookieToken = request.cookies[CSRF_COOKIE_NAME];
    if (typeof cookieToken !== 'string' || cookieToken.length !== TOKEN_LENGTH) {
      return denyCsrf(app, request, reply, 'cookie_missing');
    }

    const requestToken = extractRequestToken(request);
    if (requestToken === null) {
      return denyCsrf(app, request, reply, 'request_token_missing');
    }

    // 1. Cookie ↔ request body/header (double-submit consistency).
    if (!safeEqualToken(cookieToken, requestToken)) {
      return denyCsrf(app, request, reply, 'double_submit_mismatch');
    }

    // 2. Cookie ↔ sessions.csrf_token (server-side binding). Rejects
    //    expired sessions automatically because `read()` returns null
    //    once the row is past its idle or absolute timeout.
    const session = await readSession(sid);
    if (session === null) {
      return denyCsrf(app, request, reply, 'session_invalid');
    }
    if (!safeEqualToken(cookieToken, session.csrfToken)) {
      return denyCsrf(app, request, reply, 'session_token_mismatch');
    }

    // All three tokens agree — pass through to the route handler.
    return;
  });
}
